# Generated by Django 5.1.6 on 2025-02-23 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BakingApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='rating',
            field=models.IntegerField(default=5),
        ),
    ]
