# Generated by Django 4.2 on 2025-11-21 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BakingApp', '0002_journalentry_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='journal',
            name='tags',
            field=models.ManyToManyField(related_name='journals', to='BakingApp.tag'),
        ),
    ]
